### PR TITLE
 Fix google light on pressed 

### PR DESCRIPTION
**Pull request by gersur**
Google's Branding

Normal
btn_google_signin_light_normal_web@2x
Pressed
btn_google_signin_light_pressed_web@2x

Before
before

After
after

### CODE REVIEW

**Comment by dmjones** [comment]
Thanks for raising a PR.

I'm struggling to find where Google defines what the pressed button should look like. Do you have a link to any documentation?

**Comment by gersur** [comment]
From [https://developers.google.com/identity/images/signin-assets.zip](https://developers.google.com/identity/images/signin-assets.zip)

signin-assets.zip/google_signin_buttons/web/2x/btn_google_signin_light_pressed_web@2x.png

{43BEBDBD-A856-419A-81DC-76181A60826D} png

**Comment by dmjones** [comment]
Great, thanks. I cherry-picked one of your commits and added to master. (I will update versions and changelogs myself when I push a few changes to https://pub.dartlang.org shortly).

**Comment by dmjones** [comment]
Now released in 0.4.0: https://pub.dartlang.org/packages/flutter_auth_buttons

**Pull request closed without merging**
