### PR TITLE
Corrected flogo according to updated facebook guidelines

### PR DESCRIPTION
**Pull request by chetan-cueclad**
closes #33

### CODE REVIEW

**Comment by dmjones** [comment]
Thanks for this and apologies for the delay in response. I plan to review this tomorrow.

**Comment by romatallinn** [comment]
@chetan-cueclad the color has also been changed. Can you maybe include it within this PR?

Hex #1877F2
R = 24 G = 119 B = 242

**Review by MrLightful — CHANGES_REQUESTED** [review]
@chetan-cueclad the color has also been changed. Can you maybe include it within this PR?

Hex #1877F2
R = 24 G = 119 B = 242

**Comment by dmjones** [comment]
Thanks! I've tweaked the colour and the padding. Will close this and merge in #36.

**Pull request closed without merging**
